[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
serde = "1.0.204"
serde-error = "0.1.2"
strum = "0.26.3"
strum_macros = "0.26.4"
uuid = { version = "1.10.0", features = ["serde"] }
