//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exchanges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_message: String,
    pub assistant_message: String,
    #[sea_orm(unique)]
    pub next_exchange: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::conversations::Entity")]
    Conversations,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::NextExchange",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
