//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exchanges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub key: i32,
    pub user_message: String,
    pub assistant_message: String,
    pub conversation: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::conversations::Entity",
        from = "Column::Conversation",
        to = "super::conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Conversations,
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
